fix: added sonarqube fixes
contentstack/datasync-nodejs-website-boilerplate pull request #9
Opened 2022-09-22 15:57 UTC by vkalta

2022-10-28 12:03 UTC, netrajpatel requested changes
@vkalta Update package version

2022-10-28 15:51 UTC, aravindbuilt approved these changes

2022-10-30 20:55 UTC, vkalta commented
> @vkalta Update package version

Done @netrajpatel

2022-10-31 10:21 UTC, netrajpatel approved these changes

2022-10-31 13:56 UTC, merged